remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"
title: "Portfolio"
description: "Portfolio Optimization for C++"

search_enabled: true

aux_links:
  "Portfolio on GitHub":
    - "//github.com/alandefreitas/portfolio"
  "Portfolio on CodeDocs":
    - "https://codedocs.xyz/alandefreitas/portfolio/"

aux_links_new_tab: false

footer_content: "Copyright &copy; Alan Freitas. Distributed by an <a href=\"https://github.com/alandefreitas/portfolio/tree/master/LICENSE.txt\">MIT license.</a>"
